services:
  sqlserverLocal:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverLocal
    environment:
      SA_PASSWORD: "SenhaForte123!"  
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SenhaForte123!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodbTelemetria
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: simulacaoCredito 
      MONGO_INITDB_ROOT_PASSWORD: SenhaForte123! 
