version: "3.9"
services:
  sqlserverLocal:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverLocal
    environment:
      SA_PASSWORD: "SenhaForte123!"  
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SenhaForte123!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SenhaForte123!"  
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"

    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SenhaForte123!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5

  eventhub-emulator:
    container_name: "eventhubs-emulator"
    image: "mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest"
    volumes:
      - "${CONFIG_PATH}:/Eventhubs_Emulator/ConfigFiles/Config.json"
    pull_policy: always
    ports:
      - "5672:5672"
      - "9092:9092"
      - "5300:5300"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: ${ACCEPT_EULA}
      EVENTHUBS_ROOT_KEY_VALUE: MinhaSharedAccessKey
      EVENTHUBS_NAMES: simulacao
    depends_on:
      - azurite


  azurite:
    container_name: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    pull_policy: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"